export const styles = {
  btnBlue: {
    width: 69,
    height: 69,
    borderRadius: 24,
    backgroundColor: "#3764B4",
    justifyContent: "center",
    alignItems: "center",
    fontSize: 20,
    margin: 2,
    cursor: "pointer",
  },
  btnLight: {
    width: 69,
    height: 69,
    borderRadius: 24,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    margin: 2,
    fontSize: 20,
    cursor: "pointer",
  },
  btnGray: {
    width: 69,
    height: 69,
    fontSize: 20,
    borderRadius: 24,
    backgroundColor: "#4D5057",
    justifyContent: "center",
    alignItems: "center",
    margin: 2,
    cursor: "pointer",
  },
  row: {
    maxWidth: "100%",
    flexDirection: "row",
    margin: "auto",
  },
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    color: "white",
    maxWidth: 375,
    margin: "auto",
  },
  displayBody: {
    backgroundColor: "#292A2D",
    width: "100%",
    padding: 20,
    borderRadius: 20,
  },
  calculatorDisplay: {
    color: "white",
    background: "#1c191c",
    textAlign: "end",
    paddingTop: 10,
    paddingRight: 10,
    fontSize: "5rem",
    flex: 1,
    height: 100,
    marginBottom: 20,
  },
  autoScalingText: {
    display: "inline-block",
  },
};
